apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: grafana
spec:
  storageClassName: grafana-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.11
    path: "/volume2/NFS/homelab/grafana-volume"

